# Generated by Django 4.2.7 on 2026-05-03 09:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('father_name', models.CharField(blank=True, max_length=200)),
                ('cnic', models.CharField(max_length=15, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(default='Gujranwala', max_length=100)),
                ('meter_number', models.CharField(max_length=50, unique=True)),
                ('meter_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial')], default='residential', max_length=20)),
                ('connection_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('disconnected', 'Disconnected')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GasBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=20, unique=True)),
                ('billing_month', models.DateField()),
                ('due_date', models.DateField()),
                ('units_consumed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gas_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fixed_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('meter_rent', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=17.0, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('previous_arrears', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('partial', 'Partial'), ('waived', 'Waived')], default='unpaid', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='bills.customer')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-billing_month'],
            },
        ),
        migrations.CreateModel(
            name='GasTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slab', models.CharField(choices=[('slab1', 'Slab 1 (0–100 units)'), ('slab2', 'Slab 2 (101–300 units)'), ('slab3', 'Slab 3 (301–500 units)'), ('slab4', 'Slab 4 (500+ units)')], max_length=10, unique=True)),
                ('min_units', models.PositiveIntegerField(default=0)),
                ('max_units', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited', null=True)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('fixed_charges', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('effective_from', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['min_units'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('easypaisa', 'EasyPaisa'), ('jazzcash', 'JazzCash'), ('online', 'Online Portal'), ('cheque', 'Cheque')], default='cash', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='completed', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bills.gasbill')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField()),
                ('previous_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_consumed', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('estimated', 'Estimated'), ('confirmed', 'Confirmed')], default='pending', max_length=10)),
                ('reader_name', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='bills.customer')),
            ],
            options={
                'ordering': ['-reading_date'],
            },
        ),
        migrations.AddField(
            model_name='gasbill',
            name='meter_reading',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='bills.meterreading'),
        ),
        migrations.AddField(
            model_name='gasbill',
            name='tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='bills.gastariff'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('billing', 'Billing Issue'), ('leakage', 'Gas Leakage'), ('pressure', 'Low Pressure'), ('meter', 'Meter Problem'), ('disconnection', 'Wrongful Disconnection'), ('other', 'Other')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=15)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='bills.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
